Loading python/zen2/3.8.12
  Loading requirement: matplotlib/3.4.3/zen2
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
=============================================================================
Warning: particle_families are modified at /site-packages/yt/frontends/ramses
=============================================================================
=============================================================================
Warning: particle_families are modified at /site-packages/yt/frontends/ramses
=============================================================================
=============================================================================
Warning: particle_families are modified at /site-packages/yt/frontends/ramses
=============================================================================
=============================================================================
Warning: particle_families are modified at /site-packages/yt/frontends/ramses
=============================================================================
[compute-b7-56.zaratan.umd.edu:2876865] 3 more processes have sent help message help-mpi-common-cuda.txt / dlopen failed
[compute-b7-56.zaratan.umd.edu:2876865] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
********************************************************************
 rendering gas properties movie 
********************************************************************
********************************************************************
 rendering gas properties movie 
********************************************************************
> running filter_snapshots
> processing ramses_snapshot
> found 212 snapshots
> running filter_snapshots
> processing ramses_snapshot
> found 212 snapshots
> returning 59
>>> done 
> returning 59
>>> done 
> creating container ../../container_tiramisu/renders/haloD_varSFE_Lfid_Salp_ks20231024/LFiducialGas
> creating container ../../container_tiramisu/renders/haloD_varSFE_Lfid_Salp_ks20231024/LFiducialGas
********************************************************************
 rendering gas properties movie 
********************************************************************
> running filter_snapshots
> processing ramses_snapshot
> found 212 snapshots
> returning 59
>>> done 
********************************************************************
 rendering gas properties movie 
********************************************************************
# ____________________________________________________________________
/scratch/zt1/project/ricotti-prj/user/fgarcia4/ramses_current_runs/galaxies/data/cluster_evolution/haloD_varSFE_Lfid_Salp_ks20231024/output_00217/info_00217.txt
# ____________________________________________________________________
/scratch/zt1/project/ricotti-prj/user/fgarcia4/ramses_current_runs/galaxies/data/cluster_evolution/haloD_varSFE_Lfid_Salp_ks20231024/output_00217/info_00217.txt
> running filter_snapshots
> processing ramses_snapshot
> found 212 snapshots
> returning 59
>>> done 
# ____________________________________________________________________
/scratch/zt1/project/ricotti-prj/user/fgarcia4/ramses_current_runs/galaxies/data/cluster_evolution/haloD_varSFE_Lfid_Salp_ks20231024/output_00217/info_00217.txt
  File "/scratch/zt1/project/ricotti-prj/user/fgarcia4/tiramisu/movie_wzrd/gas_properties.py", line 165, in <module>
    check_path(render_container)
  File "/scratch/zt1/project/ricotti-prj/user/fgarcia4/tiramisu/movie_wzrd/../tools/check_path.py", line 7, in check_path
    os.makedirs(path)
  File "/cvmfs/hpcsw.umd.edu/spack-software/2022.06.15/linux-rhel8-zen2/gcc-9.4.0/python-3.8.12-m4izbfupod72qgxj4xogsl2vmivojcew/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
P002 yt : [ERROR    ] 2024-02-20 00:36:46,968 FileExistsError: [Errno 17] File exists: '../../container_tiramisu/renders/haloD_varSFE_Lfid_Salp_ks20231024/LFiducialGas'
P002 yt : [ERROR    ] 2024-02-20 00:36:46,968 Error occurred on rank 2.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
